CREATE TABLE IF NOT EXISTS `words` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `word` text CHARACTER SET utf8 NOT NULL,
  `descr` text CHARACTER SET utf8 NOT NULL,
  `trans` text CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;