<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="css/style_browse.css">
		<link rel="stylesheet" type="text/css" href="css/style_about_us.css">
		<link rel="stylesheet" type="text/css" href="css/style_panel.css">
	    <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
	    <script type="text/javascript" src="js/main.js"></script>
		<title>My vocabulary</title>
	</head>
	<body>
		<?php include "panel.phtml"; ?>
		<h1>About vocabulary</h1>
		<p>This is very convinient and practic site for improving English. Here is a lot of interesting information for people with different levels of English. If you will be practicing even 20 minuts per day - you certanly will get a perfect result! Just try...</p>
	</body>
</html>