<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Add form</title>
</head>
<body>
<link rel="stylesheet" type="text/css" href="css/style_add.css">
<p align="center"><a href="/translator/main.php" class="c">Return to main page</a></p>
<br/><br/>
 <?php if(isset($warning)):?>
	<p class='answer_bad'><?=$warning;?></p>
 <?php endif;?>
 
 <?php if(isset($msg)):?>
	<p class='answer_good'><?=$msg;?></p>
 <?php endif;?>
 
 <table align="center" class="text">
	<form id="add_form" action='' method=post>
		<tr>
			<td>Enter word (EN) :</td>
			<td><input class="input-width" type="text" name="word"></td>
		</tr>
		<tr>
			<td>Enter description : </td>
			<td><textarea class="input-width" name="descr"></textarea></td>
		</tr>
		<tr>
			<td>Enter translate (RU) : </td>
			<td><textarea class="input-width" name="trans"></textarea></td>
			<td><img width=30px src="img/question.png" 
			title=
"При   добавлении   нескольких   вариантов
перевода отделяйте каждый новый вариант
переводом строки." alt="Image not found."></td>
		</tr>
		<tr>
			<td align="right" colspan="2" ><a href="#" class="c" onclick="document.getElementById('add_form').submit();">Add</a></td>
		</tr>
	</form>
</table>


</body>