<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="css/style_registration.css">
	<title>Authorisation</title>
</head>
<body>
	<div class="table-title">
		<h1 align="center">Authorisation form</h1>
	</div>
	<?php if(isset($warning)):?>
		<p class='answer_bad'><?=$warning;?></p>
	<?php endif;?>
	<?php if(isset($msg)):?>
		<p class='answer_good'><?=$msg;?></p>
	 <?php endif;?>
	 <?php if(isset($congratulation)):?>
		<p class='answer_good'><?=$congratulation;?></p>
	 <?php endif;?>
	 <table align="center" class="text">
		<form action = "" method = "POST">
			<tr>
				<td>Enter your email: </td>
				<td><input class="input-width" type="email" name="email" /></td>
			</tr>
			<tr>
				<td>Enter your pass: </td>
				<td><input class="input-width" type="password" name="pass" /></td>
			</tr>
			<tr>
				<td>Remember me <input type = 'checkbox' name = 'remember' value='true'></td>
				<td align="right" colspan="2" ><input class="c" type = "submit" value = "OK" name = 'ok' /></td>
			</tr>
		</form>
	</table>
</body>
</html>