<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/style_main.css">
	<link rel="stylesheet" type="text/css" href="css/style_panel.css">
    <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
	<title>My vocabulary</title>
</head>
<body>
	<?php include "panel.phtml"; ?>
	<?php if(isset($_GET['cong'])): ?>
		<p class='answer_good'><?=$msg;?></p>
	<?php endif; ?>
	<div class="table-title">
		<a href="<?=$router->getUrl('revise'); ?>" class="c right">Revise</a>
		<a href="<?=$router->getUrl('wordAdd'); ?>" class="c right">Add new word</a>
		<a href="excelExport.php" class="c right">Text Export</a>
		<h1 align="center">Vocabulary</h1>
	</div>
	<h2 class='align-center'>You don't have any words in your dictionary. You can add them <a href="<?=$router->getUrl('wordAdd'); ?>">here</a>.</h2>
</body>
</html>