<div id="panel">
	<a href="<?=$router->getUrl('aboutUs') ?>" id="panel_link">About</a> |
	<a href="<?=$router->getUrl('browse') ?>" id="panel_link">Browse</a> |
	<a href="<?=$router->getUrl('wordRandom') ?>" id="panel_link">Get rand word</a> |
	<a href="<?=$router->getUrl('usersList') ?>" id="panel_link">Users list</a> |
	Hello, <?= "$email" . " !";?> | <a href="<?=$router->getUrl('authorisation') ?>" id="panel_link">Logout</a>
</div>