<html>
	<head>
		<link rel="stylesheet" type="text/css" href="css/style_revise.css">
		<link rel="stylesheet" type="text/css" href="css/style_panel.css">
		<script src="js/revise/main.js"></script>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Revise</title>
	</head>
	<body>
		<?php include "panel.phtml"; ?>
		<div class="table-fill">
			<div id='imgOkSign'><img src="./img/ok.png"/></div>
			<div class='bigEngWord'>apple</div>
			<div id='translationVariants'>
				<div class='variant1'>яблоко</div>
				<div class='variant2'>селедка</div>
			</div>
		</div>
	</body>
</html>