<html>
	<head>
		<link rel="stylesheet" type="text/css" href="css/style_revise.css">
		<link rel="stylesheet" type="text/css" href="css/style_panel.css">
		<link rel="stylesheet" type="text/css" href="css/style_revise_diagram.css">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Revise</title>
	</head>
	<body>
		<?php include "panel.phtml"; ?>
		<div class="table-fill">
			<div id='imgOkSign'><img src="./img/ok.png"/></div>
			<div id="progress"></div>
			<div class='bigEngWord' id="word">apple</div>
			<div id='translationVariants'>
				<div id='variant1'></div>
				<div id='variant2'></div>
			</div>
		</div>
		


		<!-- hidden table with revise's results -->

		<div id="resultTable">
			<section id="diagramBg">
				<ul>
					<li><hr/></li>
					<li><hr/></li>
					<li><hr/></li>
					<li><hr/></li>
					<li><hr/></li>
				</ul>
				<div id="bar1" class="barChart">
					<p id="text1"></p>
					<p id="name1" class = "labels">Remember</p>
				</div>
				<div id="bar2" class="barChart">
					<p id="text2"></p>
					<p id="name2" class = "labels">Mistakes</p>
				</div>
				<div id="bar3" class="barChart">
					<p id="text3"></p>
					<p id="name3" class = "labels">Time out</p>
				</div>
			</section>
		</div>

		<script src="js/jquery-1.9.1.min.js"></script>
		<script src="js/ProgressBar.min.js"></script>
		<script src="js/revise/main.js"></script>
		<script src="js/revise/diagram.js"></script>
	</body>
</html>