<html>
	<head>
		<link rel="stylesheet" type="text/css" href="css/style_revise.css">
		<link rel="stylesheet" type="text/css" href="css/style_panel.css">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Revise</title>
	</head>
	<body>
		<?php include "panel.phtml"; ?>
		<div class="table-fill">
			<div id='imgOkSign'><img src="./img/ok.png"/></div>
			<div id="progress"></div>
			<div class='bigEngWord' id="word">apple</div>
			<div id='translationVariants'>
				<div id='variant1'></div>
				<div id='variant2'></div>
			</div>
		</div>
		<script src="js/jquery-1.9.1.min.js"></script>
		<script src="js/ProgressBar.min.js"></script>
		<script src="js/revise/main.js"></script>
	</body>
</html>