<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Diagram of sales</title>
	<link rel="stylesheet" type="text/css" href="../css/style_revise.css">
	<link rel="stylesheet" type="text/css" href="../css/style_revise_diagram.css">
	<link rel="stylesheet" type="text/css" href="../css/style_panel.css">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
	
	<div id="wrapper">
		<section id="diagramBg">
			<ul>
				<li><hr/></li>
				<li><hr/></li>
				<li><hr/></li>
				<li><hr/></li>
				<li><hr/></li>
			</ul>
			<div id="bar1" class="barChart">
				<p id="text1"></p>
				<p id="name1" class = "labels">Cruft Inc.</p>
			</div>
			<div id="bar2" class="barChart">
				<p id="text2"></p>
				<p id="name2" class = "labels">Dorothy Production</p>
			</div>
			<div id="bar3" class="barChart">
				<p id="text3"></p>
				<p id="name3" class = "labels">Gregory & Sons Inc.</p>
			</div>
		</section>
	</div>
	
	<script src="../js/revise/diagram.js"></script>
</body>
</html>