<link rel="stylesheet" type="text/css" href="css/style_users_list.css">
<link rel="stylesheet" type="text/css" href="css/style_panel.css">
<title>User list</title>
<body>
<?php include "panel.phtml"; ?>
<?php if(isset($_GET['cong'])): ?>
	<p class='answer_good'><?=$msg;?></p>
<?php endif; ?>
<div class="table-title">
	<h1 align="center">Users list</h1>
</div>
<table class="table-fill">
	<thead>
		<tr>
			<th class="text-left">ID</th>
			<th class="text-left">User</th>
			<th class="text-left">Email</th>
			<th class="text-left">Delete</th>
			<th class="text-left">Edit</th>
		</tr>
	</thead>
	<tbody class="table-hover">
		<?php foreach($users_list as $row):?>
		<tr>
			<td> <?=$row['id']?></td>
			<td> <?=$row['user'] ?></td>
			<td> <?=$row['email'] ?></td>
			<td>
				<a name="del" href="<?=$router->getUrl('user-delete', array('num'=>$row['id'])) ?>">
					<img width=20px src="img/delete.png" title="Remove this user">
				</a>
			</td>
			<td>
				<a name="del" href="<?=$router->getUrl('user-edit', array('num'=>$row['id'])) ?>">
					<img width=40px src="img/edit.png" title="Edit user's name">
				</a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
